// <auto-generated />
using System;
using ApartmanYonetim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApartmanYonetim.Migrations
{
    [DbContext(typeof(KayitContext))]
    [Migration("20250511175511_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Entities.Models.Calisan", b =>
                {
                    b.Property<int>("CalisanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalisanAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gorev")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("CalisanId");

                    b.ToTable("Calisans");

                    b.HasData(
                        new
                        {
                            CalisanId = 11,
                            CalisanAdi = "Ahmet Yılmaz",
                            Gorev = "Çöpleri Topla",
                            Mail = "ahmet@gmail.com",
                            Sifre = "1234",
                            Telefon = "0575 486 33 12"
                        });
                });

            modelBuilder.Entity("Entities.Models.Duyuru", b =>
                {
                    b.Property<int>("DuyuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .HasColumnType("TEXT");

                    b.HasKey("DuyuruId");

                    b.ToTable("Duyurus");
                });

            modelBuilder.Entity("Entities.Models.Gorev", b =>
                {
                    b.Property<int>("GorevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GorevAd")
                        .HasColumnType("TEXT");

                    b.HasKey("GorevId");

                    b.ToTable("Gorevs");

                    b.HasData(
                        new
                        {
                            GorevId = 1,
                            Durum = true,
                            GorevAd = "Çöpleri Topla"
                        });
                });

            modelBuilder.Entity("Entities.Models.Kullanici", b =>
                {
                    b.Property<int?>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciId");

                    b.ToTable("Kullanicis");

                    b.HasData(
                        new
                        {
                            KullaniciId = 1,
                            KullaniciAd = "Fatma Açıkgöz",
                            Mail = "fatma@gmail.com",
                            Sifre = "1234",
                            Telefon = "0555 444 33 22"
                        },
                        new
                        {
                            KullaniciId = 2,
                            KullaniciAd = "Sinem Kaya",
                            Mail = "sinem@gmail.com",
                            Sifre = "1234",
                            Telefon = "0523 414 33 22"
                        },
                        new
                        {
                            KullaniciId = 3,
                            KullaniciAd = "Ali Tulup",
                            Mail = "ali@gmail.com",
                            Sifre = "1234",
                            Telefon = "0509 314 45 45"
                        },
                        new
                        {
                            KullaniciId = 4,
                            KullaniciAd = "Erkut Demirci",
                            Mail = "erkut@gmail.com",
                            Sifre = "1234",
                            Telefon = "0595 416 57 19"
                        },
                        new
                        {
                            KullaniciId = 5,
                            KullaniciAd = "Umut Kaya",
                            Mail = "umut@gmail.com",
                            Sifre = "1234",
                            Telefon = "0556 364 11 00"
                        },
                        new
                        {
                            KullaniciId = 6,
                            KullaniciAd = "Mehmet Dinçer",
                            Mail = "mehmet@gmail.com",
                            Sifre = "1234",
                            Telefon = "0567 444 33 22"
                        },
                        new
                        {
                            KullaniciId = 7,
                            KullaniciAd = "Sueda İnce",
                            Mail = "sueda@gmail.com",
                            Sifre = "1234",
                            Telefon = "0544 567 17 17"
                        },
                        new
                        {
                            KullaniciId = 8,
                            KullaniciAd = "Sudenaz Gündüz",
                            Mail = "sudenaz@gmail.com",
                            Sifre = "1234",
                            Telefon = "0543 419 45 57"
                        },
                        new
                        {
                            KullaniciId = 9,
                            KullaniciAd = "Selin Poyraz",
                            Mail = "selin@gmail.com",
                            Sifre = "1234",
                            Telefon = "0557 654 75 45"
                        },
                        new
                        {
                            KullaniciId = 10,
                            KullaniciAd = "Esra Kasap",
                            Mail = "esra@gmail.com",
                            Sifre = "1234",
                            Telefon = "0585 325 93 22"
                        },
                        new
                        {
                            KullaniciId = 11,
                            KullaniciAd = "Ahmet Yılmaz",
                            Mail = "ahmet@gmail.com",
                            Sifre = "1234",
                            Telefon = "0575 486 33 12"
                        });
                });

            modelBuilder.Entity("Entities.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAd")
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OdemeBilgisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OdenecekTutar")
                        .HasColumnType("INTEGER");

                    b.HasKey("OdemeId");

                    b.ToTable("Odemes");
                });
#pragma warning restore 612, 618
        }
    }
}
